export const NAVIGATION_AUTHEN = 'NAVIGATION_AUTHEN';
export const NAVIGATION_LOGIN_SCREEN = 'NAVIGATION_LOGIN_SCREEN';
export const NAVIGATION_REGISTER_SCREEN = 'NAVIGATION_REGISTER_SCREEN';

export const NAVIGATION_MAIN = 'NAVIGATION_MAIN';

export const NAVIGATION_TAB_HOME = 'NAVIGATION_TAB_HOME';
export const NAVIGATION_HOME_SCREEN = 'NAVIGATION_HOME_SCREEN';
export const NAVIGATION_DETAIL_HOME_SCREEN = 'NAVIGATION_DETAIL_HOME_SCREEN';

export const NAVIGATION_TAB_SETTING = 'NAVIGATION_TAB_SETTING';
export const NAVIGATION_SETTING_SCREEN = 'NAVIGATION_SETTING_SCREEN';
export const NAVIGATION_DETAIL_SETTING_SCREEN =
  'NAVIGATION_DETAIL_SETTING_SCREEN';
